apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
  namespace: pujitha
spec:
  selector:
    app: helloworld-app
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
